Unity should be capitalized
aarthificial/pixelgraphics pull request #11
Opened 2022-06-06 19:59 UTC by BenHerbst

2022-06-06 23:41 UTC, aarthificial requested changes
Commit messages should follow [Angular Commit Message Conventions](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format).

I suggest "docs: fix capitalization"

2022-06-10 19:08 UTC, BenHerbst commented
I changed the message

2022-06-10 19:51 UTC, aarthificial approved these changes

2022-06-10 19:52 UTC, merged

2022-06-10 19:53 UTC, aarthificial commented
Thank you